# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20cbaea9d8ae9406c9d5c59b96daf81e8d7f6d972a4c2dc73cc2c1cf279571d51cc90f21cfa1c850d8274c01ff5dfe855a3bc312b4ed8d5706988a3d6be6b6a1

test:
  secret_key_base: d022bfee3dabb948dfcbdf5931bf427993e02b393c52fa3f5f71b09640febee08f0d1bd063b6aa44a7e0cb0c4359f692c8072ef04f12fd554181bfa0702087e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
